### PR TITLE
test: add assertions to hurl files

### PR DESCRIPTION
**Pull request by robinstraub**
This PR adds a hurl execution script 

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Testing
- [ ] Other (please describe):

# What is the current behavior?

Currently hurl files have to run one by one.

Issue Number: #387 

# What is the new behavior?

Hurls can be executed with a single script.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Comment by robinstraub** [comment]
7 hurl tests are still failing, I wrote a summary [here](https://gist.github.com/robinstraub/fbb5460e465ce73c8a1bb91d97d7c14d).

**Comment by robinstraub** [comment]
Hurl files can be run in one line with a `hurl --test examples/*` and there is no need for a specific sequence (hurl files are independant). There is less value to write a script that just runs this command so I arbitrarily reduced the PR scope to only improve hurl files by fixing formatting and adding assertions (so the hurl files actually test something)

**Comment by phklive** [comment]
Please rebase

**Comment by robinstraub** [comment]
```
$ hurl --test examples/**/*.hurl
--------------------------------------------------------------------------------
Executed files:  49
Succeeded files: 49 (100.0%)
Failed files:    0 (0.0%)
Duration:        27124 ms
```

Every hurl test completes with the latest commit

**Pull request merged**
