### PR TITLE
"Fix: Wrap Contract Address Parameter in Array for starknet_getContractStorageProof Hurl Test"

### PR DESCRIPTION
**Pull request by joshualyguessennd**
# Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Currently, the starknet_getContractStorageProof method takes the keys parameter as a direct string, which is inconsistent with some endpoints that may expect this address within an array.

Issue Number:  https://github.com/keep-starknet-strange/beerus/issues/468

# What is the new behavior?

With the changes introduced in this PR, the keys parameter is now provided within an array structure. This provides better compatibility with some endpoints and should prevent possible errors or inconsistencies with these endpoints. This change does not introduce any breaking changes and is backward-compatible, as it merely changes the format of a parameter.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Comment by joshualyguessennd** [comment]
> Could you show me what endpoints need the contract_address as a string in an array?
> 
> SCR-20230531-oyiz
> I have these specs for contract_address on another method

**Comment by joshualyguessennd** [comment]
I have edit the PR, it's the keys that need to be in an array of string not the contract_address 
https://github.com/keep-starknet-strange/beerus/blob/cd62a08f4bc00d9d277524a63d20894c641078a7/crates/beerus-rpc/src/lib.rs#L437-L457

**Review by drspacemn — COMMENTED** [review]
I see the following error on when running this hurl:
``` 
 --> examples/beerus-rpc/additional/starknet_getContractStorageProof.hurl:20:0
   |
20 | jsonpath "$.error" not exists
   |   actual:   object
   |   expected: not something
   |
```

**Comment by joshualyguessennd** [comment]
@drspacemn you have this issue because of your starknet RPC endpoint switch from infura to Alchemy. cause infura doesn't handle `pathfinder_getProof` yet

**Pull request merged**
