### PR TITLE
feat: add stark_block_transaction_count RPC endpoint

### PR DESCRIPTION
**Pull request by dpinones**
- [x] Implemented stark_blockTransactionCount
- [ ] Add tests
- [ ] Add docs
- [ ] Deprecate REST API code

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Not implemented

Issue Number: #222 

# What is the new behavior?

Making a request to JSON-RPC "stark_blockTransactionCount" returns the number of transactions in a block on Starknet.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Comment by dpinones** [comment]
To create the tests, it would be advisable to have a [mock](https://github.com/sayajin-labs/kakarot-rpc/blob/main/core/src/utils/wiremock_utils.rs) similar to the one used in `kakarot_rpc`. If so, where should we add this mock?

**Comment by dpinones** [comment]
We should also add the [documentation](https://github.com/sayajin-labs/kakarot-rpc/blob/main/docs/methods/eth_getBlockByNumber.md) similar to what was done in `kakarot_rpc`. If so, where should we add this documentation?

**Comment by drspacemn** [comment]
> We should also add the [documentation](https://github.com/sayajin-labs/kakarot-rpc/blob/main/docs/methods/eth_getBlockByNumber.md) similar to what was done in `kakarot_rpc`. If so, where should we add this documentation?

Is there any autogen here or are all those docs handwritten?

**Comment by drspacemn** [comment]
> We should also add the [documentation](https://github.com/sayajin-labs/kakarot-rpc/blob/main/docs/methods/eth_getBlockByNumber.md) similar to what was done in `kakarot_rpc`. If so, where should we add this documentation?

Issue created: https://github.com/keep-starknet-strange/beerus/issues/243

**Review by drspacemn — APPROVED** [review]

**Pull request merged**
