### PR TITLE
test: added initial helios light client test

### PR DESCRIPTION
**Pull request by startup-dreamer**
# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation content changes
- [ ] Build-related changes
- [x] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #497 

# What is the new behavior?

Added initital tests for the helios light client to check whether i am on the right direction

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Comment by Aragar199** [comment]
@startup-dreamer Thank you for the PR! Please move this into a separate helios.rs file, these will be kept separate from the beerus.rs tests. Next steps would be adding tests for uses in https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/src/lightclient/ethereum/helios_lightclient.rs

**Comment by startup-dreamer** [comment]
on it @Aragar199  will do the said changes

**Comment by startup-dreamer** [comment]
Hy @Aragar199  When going through beerus integration.rs test i found these lines 
 ```       
     let mut helios_lightclient = MockEthereumLightClient::new();
        helios_lightclient
            .expect_starknet_last_proven_block()
            .return_once(move || Ok(U256::from(1)));
```
shouldn't it be named `ethereum_lightclient` instead, If i am not missing anything.

**Comment by Aragar199** [comment]
> Hy @Aragar199 When going through beerus integration.rs test i found these lines
> 
> ```
>     let mut helios_lightclient = MockEthereumLightClient::new();
>        helios_lightclient
>            .expect_starknet_last_proven_block()
>            .return_once(move || Ok(U256::from(1)));
> ```
> 
> shouldn't it be named `ethereum_lightclient` instead, If i am not missing anything.

They might be made more consistent, but can be left as is.

Also, the test in this PR is already in beerus.rs?
https://github.com/keep-starknet-strange/beerus/blob/main/crates/beerus-core/tests/beerus.rs#L1915

**Comment by startup-dreamer** [comment]
oh i must have missed it shold i move all the helios related test to helios.rs including this one for more consistency

**Comment by Aragar199** [comment]
> oh i must have missed it shold i move all the helios related test to helios_lightclient.rs including this one for more consistency

Yes this test should also be in a helios_lightclient.rs file. Thanks!

**Comment by startup-dreamer** [comment]
Hy, @Aragar199  you may merge this branch I am busy in other things so as soon as i am over them I will add more tests.

**Comment by drspacemn** [comment]
@startup-dreamer can we get an update here?

**Comment by drspacemn** [comment]
closing as inactive. feel free to rebase and reopen

**Pull request closed without merging**
