### PR TITLE
feat/migrate-l2_to_l1_messages

### PR DESCRIPTION
**Pull request by Aragar199**
# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #217 

# What is the new behavior?

Migrate l2_to_l1_messages and add tests on beerus_rpc.

-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by drspacemn — COMMENTED** [review]
when running the hurl I'm seeing 
```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"invalid hex character: m, at 0 at line 1 column 10"},"id":1}
```
and these error logs from the server:
```
[2023-03-10T17:50:05Z ERROR jsonrpsee_types::params] [next_inner] Deserialization to "primitive_types::U256" failed. Error: Error("invalid hex character: m, at 0", line: 1, column: 10), input JSON: "\"msg_hash\"]"
[2023-03-10T17:50:05Z ERROR beerus_rpc::beerus_rpc_server] Error parsing "msg_hash" as "U256": InvalidParams(invalid hex character: m, at 0 at line 1 column 10)
```

**Comment by Aragar199** [comment]
@drspacemn Oh I misunderstood how to construct the example. I put "msg_hash" to indicate placing a msg_hash string as a parameter. Is this how it should be instead?

`POST http://0.0.0.0:3030
Content-Type: application/json
{
    "jsonrpc":"2.0",
    "method":"l2_to_l1_messages",
    "params":["0x29047315f49bf7eb264ae95ded6c5cb858d86106f863f31f4f49c1ce4b1321c0"],
    "id":1
}`

I incorrectly assumed this was a template instead of an example and not include the parameter as a string. Does that mean we should have parameters for testnet vs mainnet?

**Comment by drspacemn** [comment]
> @drspacemn Oh I misunderstood how to construct the example. I put "msg_hash" to indicate placing a msg_hash string as a parameter. Is this how it should be instead?
> 
> `POST http://0.0.0.0:3030 Content-Type: application/json { "jsonrpc":"2.0", "method":"l2_to_l1_messages", "params":["0x29047315f49bf7eb264ae95ded6c5cb858d86106f863f31f4f49c1ce4b1321c0"], "id":1 }`
> 
> I incorrectly assumed this was a template instead of an example and not include the parameter as a string. Does that mean we should have parameters for testnet vs mainnet?

let's stick with mainnet. That is what the other hurls have now and sometimes the Goerli Consensus RPC doesn't come up cleanly

**Comment by Aragar199** [comment]
@drspacemn Looking at the other hurl example files, they are not passing in this parameter information. Are those going to be updated or is my example hurl a special case because of the feature involved? Just want to make sure I'm following the guidelines correctly.

**Comment by drspacemn** [comment]
All of the hurls should be runnable via:

`hurl <file>`

You can see this as a reference: https://github.com/keep-starknet-strange/beerus/pull/252#discussion_r1132279048

Some of the requests don't actually require parameters to still run successfully

**Pull request closed without merging**
