### PR TITLE
Implemented get_contract_storage_proof

### PR DESCRIPTION
**Pull request by phklive**
Implemented get_contract_storage_proof

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Not implemented

Issue Number: #296 

# What is the new behavior?

Given params returns contract storage proof

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

Needs testing

### CODE REVIEW

**Comment by phklive** [comment]
@drspacemn this pr needs testing, i wasn't able to make sure given the right params it returns the right data but the implementation lgtm. I think we should close all rpc endpoints then add tests for all. wdyt ?

**Comment by phklive** [comment]
Also everytime it adds this no new line at end of file: 
SCR-20230406-kqrm

I am confused do we need a new line at EOF or not?

**Comment by drspacemn** [comment]
> @drspacemn this pr needs testing, i wasn't able to make sure given the right params it returns the right data but the implementation lgtm. I think we should close all rpc endpoints then add tests for all. wdyt ?

yeah this sounds good to me. 

As for new line at EOF yeah typically a good formatting practice

**Review by drspacemn — APPROVED** [review]
lgtm

**Pull request merged**
