### PR TITLE
Starknet: RPC Get_nonce - Core, CLI, RestAPI implementation + test

### PR DESCRIPTION
**Pull request by danilowhk**
Implemented query-nonce RPC call for Beerus.

Implemented in Beerus_core, beerus_cli, beerus_restapi + nominal and error tests for each

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: N/A

# What is the new behavior?

-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

### CODE REVIEW

**Review by abdelhamidbakhta — CHANGES_REQUESTED** [review]
DS Store files should be ignored

**Comment by abdelhamidbakhta** [comment]
> 

yess

**Comment by danilowhk** [comment]
> > 
> 
> yess

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Pull request merged**
