### PR TITLE
feat: add test starknet_getBlockWithTxHashes RPC

### PR DESCRIPTION
**Pull request by dpinones**
* Implemented test for RPC

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #342 

# What is the new behavior?

-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Review by drspacemn — APPROVED** [review]
lgtm

**Comment by phklive** [comment]
Was reviewing, got merged lol

**Comment by drspacemn** [comment]
@phklive was there more to discuss here. Did you need an issue reopened around this?

**Comment by phklive** [comment]
Absolutely not, just saw the status change while reviewing but it lgtm

**Pull request merged**
