### PR TITLE
fix: remove short attribute to avoid collision

### PR DESCRIPTION
**Pull request by dpinones**
* remove `short` attribute to avoid option name collision
# Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #366 

# What is the new behavior?

Beerus CLI works correctly and does not throw the option collision error.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Review by phklive — COMMENTED** [review]
What type of "collision" did the short attribute add?

**Comment by dpinones** [comment]
> 
Basically, if you run a CLI command that receives parameters, it doesn't work. According to the `clap` documentation, if no value is assigned to the `short` attribute, it takes the first character of the field name by default. This is causing a collision for us. That's why I removed the short attribute.
Moreover, using the short attribute in this way does not seem appropriate for the ux. We should create a discussion to ensure that our CLI has the best ux.

**Comment by phklive** [comment]
The CLI will be rebuilt as one of the next steps before release of V1 to improve UX and use what we have improved for the RPC. 

This PR is interesting but not needed at this moment.

We should focus for now on finalizing the tests for the RPC.

**Comment by phklive** [comment]
Just tried: 

cargo r --bin beerus starknet query-nonce --address xxx

On main and it worked, can you test please.

**Comment by phklive** [comment]
The current focus is unaligned with PR and CLI might be deprecated, if not this pr will be merged.

**Pull request closed without merging**
