### PR TITLE
Addition of first ethereum endpoint: feat/ethereum_blockNumber

### PR DESCRIPTION
**Pull request by phklive**
Addition of first ethereum endpoint: feat/ethereum_blockNumber

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?
Ethereum endpoints are not implemented

Issue Number: #290 

# What is the new behavior?

The endpoint has been added + boilerplate to add other eth endpoints

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

Addition of test boilerplate for eth endpoints is needed to be able to test these new endpoints

### CODE REVIEW

**Comment by phklive** [comment]
I have added the first eth_endpoint: ethereum_blockNumber, also i have renamed the existing endpoints to starknet_ to be able to defferentiate between eth and stark.

Next step would be to add tests.

**Comment by drspacemn** [comment]
If possible I prefer to keep the namespaced version of the RPC server. I’m fairly certain jsonrpsee allows you to extend the server methods with another namespace

**Comment by phklive** [comment]
Resolved conflicts, ready to merge 👍

**Review by drspacemn — APPROVED** [review]
lgtm

**Pull request merged**
