### PR TITLE
dev: rust-toolchain.toml declaration/file refactor

### PR DESCRIPTION
**Pull request by drspacemn**
Explicitly declare toolchain as `nightly` in `rust-toolchain.toml`
Update installer and README to reflect.
Move env example to examples.
Remove stale artifact `report.json`(please double check and let me know, I did not see anything ingesting it)

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Installer checks whether rust default is set to nightly.

Issue Number: N/A

# What is the new behavior?

cargo build can leverage the toolchain declaration 
-
-
-

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

Please double check `report.json` is okay for removal. Do we want to purge it from the git history?

### CODE REVIEW

**Review by abdelhamidbakhta — APPROVED** [review]
Lgtm

**Comment by drspacemn** [comment]
Actually I think `report.json` will be generated again if this workflow isn't removed: 
https://github.com/keep-starknet-strange/beerus/blob/main/.github/workflows/test.yml#L50-L55

**Review by LucasLvy — CHANGES_REQUESTED** [review]
Directly generate lcov file instead of json

**Review by LucasLvy — APPROVED** [review]
lgtm

**Pull request merged**
