### PR TITLE
Implemented Feat/get_block_transaction_count

### PR DESCRIPTION
**Pull request by phklive**
# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Not implemented

Issue Number: #182 

# What is the new behavior?

- Return number of transactions in a block

# Does this introduce a breaking change?

- [ ] Yes
- [X] No

# Other information

Depends on pull #197

### CODE REVIEW

**Comment by drspacemn** [comment]
Is this still dependent on @danilowhk new Node/Payload impl. If so can you move to a draft?

**Comment by phklive** [comment]
> Is this still dependent on @danilowhk new Node/Payload impl. If so can you move to a draft?

Yes i do think so. 

I will.

**Comment by phklive** [comment]
@all-contributors please add @phklive

**Comment by phklive** [comment]
@all-contributors please add @phklive  for Code

**Comment by phklive** [comment]
@all-contributors please add @phklive  for code

**Comment by drspacemn** [comment]
please rebase, and `beerus_rest_api` support can be removed

**Pull request closed without merging**
