### PR TITLE
Feat: Add Verification Layer to "Starknet : get_block_with_tx_hashes

### PR DESCRIPTION
**Pull request by irisdv**
Add Verification Layer to "Starknet : get_block_with_tx_hashes

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

Issue Number: #180 

# What is the new behavior?
-

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

# Other information

### CODE REVIEW

**Comment by drspacemn** [comment]
please rebase, and `beerus_rest_api` support can be removed

**Comment by irisdv** [comment]
I rebased with main, I'm just having an issue with the status field in `BlockWithTxHashes` because `BlockWithTxs` does not have a status field, what would be the best way to get it in your opinion ?

**Comment by drspacemn** [comment]
I'm seeing a status field when curling infura:
```
curl --location --request POST 'https://starknet-goerli.infura.io/v3/<INFURA_KEY>' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc":"2.0",
	"method":"starknet_getBlockWithTxs",
	"params":["latest"],
	"id":1
}'
```

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "block_hash": "0x2083ae2eca7a0d7b3f6680a7c96e253529329ec656000b890e954c0e89337e",
        "block_number": 778846,
        "new_root": "0x5707b83e160cca081b15cf16832f81b878426c09afb71022cd837d69c4b8427",
        "parent_hash": "0xcb71db33748680c800297a554738300e531121282d0df137e774f00e1d778d",
        "sequencer_address": "0x46a89ae102987331d369645031b49c27738ed096f2789c24449966da4c6de6b",
        "status": "ACCEPTED_ON_L2",
        "timestamp": 1678468881,
        ...
```

**Comment by drspacemn** [comment]
Please add testing for new functionality

**Pull request merged**
